---
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

name: Multi Arch Build for Alpine

jobs:
  build:
    name: Build Binaries with musl
    runs-on: ubuntu-22-04
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout boringtun
        uses: actions/checkout@v2
        with:
          repository: cloudflare/boringtun
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/boringtun-cli
      - id: sha
        run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
  push:
    name: docker build and push images
    needs: build
    runs-on: ubuntu-22-04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: aarch64-unknown-linux-musl
          path: linux/arm64/
      - uses: actions/download-artifact@v2
        with:
          name: armv7-unknown-linux-musleabihf
          path: linux/arm/v7/
      - uses: actions/download-artifact@v2
        with:
          name: x86_64-unknown-linux-musl
          path: linux/amd64/
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64, linux/arm, linux/amd64
          file: ./Dockerfile
          push: true
          build-args: |
            FROM=alpine:3.17
          tags: |-
            leonnicolas/boringtun:alpine
            leonnicolas/boringtun:alpine-${{ needs.build.outputs.sha }}
            ghcr.io/leonnicolas/boringtun:alpine
            ghcr.io/leonnicolas/boringtun:alpine-${{ needs.build.outputs.sha }}
