---
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

name: Multi Arch Build

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
         - target: aarch64-unknown-linux-gnu
           package: gcc-aarch64-linux-gnu
         - target: armv7-unknown-linux-gnueabi
           package: gcc-arm-linux-gnueabi
         - target: x86_64-unknown-linux-gnu
           package: ${{ null }}
    steps:
      - name: Checkout boringtun
        uses: actions/checkout@v2
        with:
          repository: cloudflare/boringtun
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: docker-build
      - name: append carg/config.toml
        run: cat docker-build/cargo.toml >> .cargo/config.toml
      - name: Install extra packages
        if: ${{ matrix.platform.package != null }}
        run: sudo apt-get -y install ${{ matrix.platform.package }}
      - name: set up rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
      - name: Build binary
        run: rustc --print target-list
      - name: Build binary
        run: cargo build --bin boringtun-cli --release --target ${{ matrix.platform.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/boringtun-cli
      - id: sha
        run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
  push:
    name: docker build and push images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: aarch64-unknown-linux-gnu
          path: linux/arm64/
      - uses: actions/download-artifact@v2
        with:
          name: armv7-unknown-linux-gnueabi
          path: linux/arm/v7/
      - uses: actions/download-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: linux/amd64/
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64, linux/arm, linux/amd64
          push: ${{github.ref_name == 'main'}}
          build-args: |
            FROM=debian:stable-slim
          tags: |-
            leonnicolas/boringtun:latest
            leonnicolas/boringtun:${{ needs.build.outputs.sha }}
            ghcr.io/leonnicolas/boringtun:latest
            ghcr.io/leonnicolas/boringtun:${{ needs.build.outputs.sha }}
